export const STRINGS = {
  appTitle: 'MOSI',
  appLongTitle: 'Manitoba Outdoor Safety Index',
  appTagline: 'Manitoba Outdoor Safety Index',
  appQuestion: 'Is it safe to be outside right now?',
  overviewEyebrow: 'Unified outdoor safety',
  overviewSubtitle: 'Live Manitoba conditions with forecast-informed context and location-aware alerts.',
  overviewOffline: 'Live sources were unavailable. Showing the most recent cached data.',
  overviewRefresh: 'Pull to refresh',
  overviewNoData: 'Data temporarily unavailable',
  overviewSeasonal: 'Based on seasonal data',
  alertsTitle: 'Alerts',
  alertsSubtitle: 'Geographically relevant alerts, filtered for your location when available.',
  mapTitle: 'Zone Map',
  mapSubtitle: 'Tap a Manitoba zone to inspect local conditions and site-specific advisories.',
  insightsTitle: 'Predictions',
  insightsSubtitle: 'Forecast-informed category outlooks for the current region.',
  aboutTitle: 'About',
  aboutSubtitle:
    'MOSI combines Manitoba weather, air quality, wildfire, water, vector, and public-health signals into one public-facing score.',
  defaultSummary: 'Data temporarily unavailable',
  lastUpdatedPrefix: 'Last updated',
  currentRegionPrefix: 'Current region',
  locationDenied: 'Location denied, using a manually selected region.',
  weatherSource: 'Environment and Climate Change Canada',
  wildfireSource: 'Canadian Wildland Fire Information System',
  waterSource: 'Province of Manitoba',
  vectorSource: 'MOSI estimate (not an official forecast)',
  healthSource: 'Manitoba Health',
  notificationTitle: 'MOSI alert',
} as const;
